### ISSUE TITLE
GEN-152: `report::from` should load recursive `.source()` information from `std::error::Error`-compatible errors

### ISSUE THREAD

**Issue by QAston** [hashintel/hash#4355] opened 2024-04-25 02:04 UTC
### Describe the bug

Report::from currently ignores nested .source() results of std::error::Error-compliant types.

For anyhow and eyre errors there's a compat module which loads their nested errors, but there's nothing like this for basic std::error::Error like the ones generated from thiserror::Error.

### To reproduce

```Rust
struct MyContext;
fn main() {
  let wrapped_client = reqwest::Client::new();
  let client = reqwest_middleware::ClientBuilder::new(wrapped_client).build()
  let response = client
     // nonexistent server
    .post("http://localhost:9999/")
    .body("asdf")
    .send()
    .await
    .change_context(MyContext);

  println!("{:?}", response)
}
```

prints error: 
```
Error: IoError
├╴at location
│
╰─▶ Request error: error sending request for url (http://localhost:9999/)
    ├╴at location
    ╰╴backtrace with 29 frames (1)
```

while it shoud include nested errors along the lines of
```
source: Error { kind: Connect, source: Some(ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
```

### Expected behavior

Errors that have std::error::Error::source() implemented in a nested manner, like [reqwest-midleware::Error](https://docs.rs/reqwest-middleware/latest/src/reqwest_middleware/error.rs.html#7) which contains [reqwest::Error](https://docs.rs/reqwest/latest/src/reqwest/error.rs.html#213) should have their sources displayed recursively in the display output.

Recursive nesting of errors is the currently default paradigm of nesting errors in the rust ecosystem and should be supported.

Example: 

Error: MyContext
├╴at location
│
╰─▶ Request error: error sending request for url (http://localhost:9999/)
    ├╴backtrace with 28 frames (1)
    ├╴at location
    ├╴error sending request for url (http://localhost:9999/)
    ├╴client error (Connect)
    ├╴tcp connect error: Connection refused (os error 111)
    ╰╴Connection refused (os error 111)
    
The above was achieved using this abomination:
```Rust
fn main() {
  let wrapped_client = reqwest::Client::new();
  let client = reqwest_middleware::ClientBuilder::new(wrapped_client).build()
  let response = client
    .post("http://localhost:9999/")
    .body("asdf")
    .send()
    .await
    .map_err(|e| anyhow::anyhow!(e))
    // result of IntoReportCompat::into_report doesn't allow for .change_context(), so we map_err ...
    .into_report().map_err(|e|e.change_context(Error::IoError))?
  println!("{:?}", response);
}
```

### Rust compiler

rustc 1.78.0-nightly (5119208fd 2024-03-02)

### Host

x86_64-unknown-linux-gnu

### Target

x86_64-unknown-linux-gnu

### Version

v0.4.1

### Features

default

**Comment by TimDiekmann** [comment] 2024-04-27 15:14
Duplicate of https://github.com/hashintel/hash/issues/2127

**Closed by TimDiekmann** 2024-04-27 15:14 UTC
Labels: state/duplicate, area/libs > error-stack, area/libs, lang/rust, category/bug

**Comment by TimDiekmann** [comment] 2024-04-27 15:17
Hi @QAston and thanks for filing this issue. I absolutely hear you and agree that the sources should be captured. I marked this as a duplicate of #2127 as this was flagged before. The main issue with that is that `source` does not return an error which is `Send + Sync`. Ideally, we would print the sources as attachments. 

One way to get a similar result now is to attach the error as string and revisit this at some point later. Happy to hear your thoughts but I'd prefer to keep the discussion in one issue 🙂

**Comment by TimDiekmann** [comment] 2024-07-12 14:26
[Part of `error-stack@0.5.0`](https://github.com/hashintel/hash/releases/tag/error-stack%400.5.0)
